export const GET_PRODUCTS ='GET_PRODUCTS'
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const EDIT_PRODUCT = 'EDIT_PRODUCT'
export const SEARCH_BY_NAME = 'SEARCH_BY_NAME'
export const ADD_ITEM = 'ADD_ITEM'
export const DELETE_ITEM = 'DELETE_ITEM'
export const DETAIL_PRODUCT = 'DETAIL_PRODUCT'
export const LOCALHOST = "http://localhost:3001/"
export const FILTER_BY_CATEGORY = 'FILTER_BY_CATEGORY'
export const GET_CATEGORIES = 'GET_CATEGORIES';