// PRODUCTOS
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const EDIT_PRODUCT = 'EDIT_PRODUCT'
export const SEARCH_BY_NAME = 'SEARCH_BY_NAME'
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const FILTER_BY_CATEGORY = 'FILTER_BY_CATEGORY'
export const ORDER_BY_PRICE = "ORDER_BY_PRICE"
export const ORDER_BY_RATE = "ORDER_BY_RATE"
// CARRITO
export const ADD_ITEM = 'ADD_ITEM'
export const REST_ITEM = "REST_ITEM"
export const DELETE_ITEM = 'DELETE_ITEM'
// export const SUM_CART = "SUM_CART"
export const UPDATE_CART = "UPDATE_CART"
// AUTENTICACION Y USUARIO
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const LOGOUT = "LOGOUT";
export const GET_USER_DETAIL = "GET_USER_DETAIL";
export const AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR";
export const UPDATE_USER = "UPDATE_USER";
// PEDIDOS
export const GET_PEDIDOS = "GET_PEDIDOS" //all
export const GET_PEDIDO_BY_USER = "GET_PEDIDO_BY_USER"
export const GET_PEDIDO_DETAIL = "GET_PEDIDO_DETAIL"
export const EDIT_STATUS_PEDIDO = "EDIT_STATUS_PEDIDO"
export const CREATE_PRODUCT = "CREATE_PRODUCT"
//Categorias
export const EDIT_CATEGORIA = "EDIT_CATEGORIA"
//Subcategorias
export const GET_SUBCATEGORIES="GET_SUBCATEGORIES"